set(ROOT "${PROJECT_SOURCE_DIR}")

function(read_project_file var path)
  if(NOT EXISTS "${ROOT}/${path}")
    message(FATAL_ERROR "Expected file to exist: ${path}")
  endif()
  file(READ "${ROOT}/${path}" content)
  set("${var}" "${content}" PARENT_SCOPE)
endfunction()

function(expect_contains content needle description)
  string(FIND "${content}" "${needle}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Expected ${description}: '${needle}'")
  endif()
endfunction()

function(expect_not_contains content needle description)
  string(FIND "${content}" "${needle}" found)
  if(NOT found EQUAL -1)
    message(FATAL_ERROR "Did not expect ${description}: '${needle}'")
  endif()
endfunction()

read_project_file(java_cmake "cmake/java.cmake")
read_project_file(java_release ".github/workflows/java_release.yml")
read_project_file(java_build ".github/workflows/java_build.yml")
read_project_file(release_workflow ".github/workflows/release.yml")
read_project_file(pom_native "java/pom-native.xml.in")
read_project_file(pom_local "java/pom-local.xml.in")
read_project_file(pom_full "java/pom-full.xml.in")

expect_contains("${java_cmake}" "JAVA_MAVEN_GROUP_ID \"io.github.liufang-robot\"" "Maven Central groupId")
expect_contains("${java_cmake}" "JAVA_ENABLE_MAVEN_CENTRAL OFF" "Maven Central plugin disabled for normal package builds")
expect_contains("${java_cmake}" [[set(JAVA_PACKAGE "${JAVA_GROUP}.${JAVA_ARTIFACT}")]] "Java package namespace remains separate from Maven groupId")
expect_contains("${java_cmake}" "linux-aarch64" "Linux arm64 native artifact id")
expect_contains("${java_cmake}" "java_native_deploy" "native Maven deploy target")
expect_contains("${java_cmake}" "java_deploy" "Java Maven deploy target")

expect_contains("${pom_native}" "<groupId>@JAVA_MAVEN_GROUP_ID@</groupId>" "native Maven groupId variable")
expect_contains("${pom_local}" "<groupId>@JAVA_MAVEN_GROUP_ID@</groupId>" "local Maven groupId variable")
expect_contains("${pom_full}" "<artifactId>lebai-linux-aarch64</artifactId>" "Linux arm64 runtime dependency")
expect_contains("${pom_full}" "@JAVA_CENTRAL_PUBLISHING_PLUGIN@" "conditional Central Portal Maven plugin")
expect_not_contains("${pom_native}" "oss.sonatype.org" "old OSSRH publishing endpoint")
expect_not_contains("${pom_local}" "oss.sonatype.org" "old OSSRH publishing endpoint")
expect_not_contains("${pom_full}" "oss.sonatype.org" "old OSSRH publishing endpoint")

expect_contains("${java_release}" "uses: actions/setup-java@v4" "modern Java setup action")
expect_contains("${java_release}" "runner: ubuntu-24.04-arm" "Linux arm64 Java release runner")
expect_contains("${java_release}" "native-id: linux-x86-64" "Linux x64 native artifact matrix value")
expect_contains("${java_release}" "native-id: linux-aarch64" "Linux arm64 native artifact matrix value")
expect_contains("${java_release}" "name: lebai-java-native-${{ matrix.native-id }}" "Linux matrix native artifact upload")
expect_contains("${java_release}" "lebai-java-native-win32-x86-64" "Windows x64 native artifact")
expect_contains("${java_release}" "name: lebai-java-jars" "aggregate Java jar artifact")
expect_contains("${java_release}" "MAVEN_CENTRAL_USERNAME" "Maven Central credential")
expect_contains("${java_release}" "MAVEN_GPG_PRIVATE_KEY" "GPG signing key")
expect_contains("${java_release}" "JAVA_ENABLE_MAVEN_CENTRAL=ON" "Central Portal plugin enabled only for deploy steps")
expect_contains("${java_release}" "java_native_deploy" "native deploy step")
expect_contains("${java_release}" "java_deploy" "main deploy step")

expect_contains("${java_build}" "uses: actions/setup-java@v4" "modern Java build setup action")
expect_contains("${java_build}" "cmake --build build --target java_package" "Java package build target")
expect_not_contains("${java_build}" "softprops/action-gh-release" "legacy Java release action")

expect_contains("${release_workflow}" "uses: ./.github/workflows/java_release.yml" "aggregate Java release workflow")
expect_contains("${release_workflow}" "name: lebai-java-jars" "aggregate Java artifact download")
expect_contains("${release_workflow}" "*.jar" "GitHub Release Java artifacts")
