set(ROOT "${PROJECT_SOURCE_DIR}")

function(read_project_file var path)
  if(NOT EXISTS "${ROOT}/${path}")
    message(FATAL_ERROR "Expected file to exist: ${path}")
  endif()
  file(READ "${ROOT}/${path}" content)
  set("${var}" "${content}" PARENT_SCOPE)
endfunction()

function(expect_contains content needle description)
  string(FIND "${content}" "${needle}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Expected ${description}: '${needle}'")
  endif()
endfunction()

function(expect_not_contains content needle description)
  string(FIND "${content}" "${needle}" found)
  if(NOT found EQUAL -1)
    message(FATAL_ERROR "Did not expect ${description}: '${needle}'")
  endif()
endfunction()

read_project_file(python_release ".github/workflows/python_release.yml")
read_project_file(release_workflow ".github/workflows/release.yml")
read_project_file(linux_python ".github/workflows/linux_python_release.yml")
read_project_file(linux_python_aarch64 ".github/workflows/linux_python_aarch64_release.yml")
read_project_file(windows_python ".github/workflows/windows_python_release.yml")

expect_contains("${python_release}" "uses: ./.github/workflows/linux_python_release.yml" "Linux x64 wheel workflow")
expect_contains("${python_release}" "uses: ./.github/workflows/linux_python_aarch64_release.yml" "Linux arm64 wheel workflow")
expect_contains("${python_release}" "uses: ./.github/workflows/windows_python_release.yml" "Windows wheel workflow")
expect_contains("${python_release}" "pattern: lebai-*-whl" "aggregate wheel download")
expect_contains("${python_release}" "python -m twine check dist/*.whl" "wheel validation before publish")
expect_contains("${python_release}" "python -m twine upload" "single PyPI publish step")
expect_contains("${python_release}" "name: lebai-python-wheels" "aggregate wheel artifact")

expect_not_contains("${linux_python}" "twine upload" "Linux x64 direct PyPI publish")
expect_not_contains("${linux_python_aarch64}" "twine upload" "Linux arm64 direct PyPI publish")
expect_not_contains("${windows_python}" "twine upload" "Windows direct PyPI publish")
expect_not_contains("${linux_python}" "tags:" "Linux x64 direct tag release trigger")
expect_not_contains("${linux_python_aarch64}" "tags:" "Linux arm64 direct tag release trigger")
expect_not_contains("${windows_python}" "tags:" "Windows direct tag release trigger")

expect_contains("${release_workflow}" "uses: ./.github/workflows/python_release.yml" "aggregate Python release workflow")
expect_contains("${release_workflow}" "name: lebai-python-wheels" "aggregate Python artifact download")
