set(ROOT "${PROJECT_SOURCE_DIR}")

function(read_project_file var path)
  if(NOT EXISTS "${ROOT}/${path}")
    message(FATAL_ERROR "Expected file to exist: ${path}")
  endif()
  file(READ "${ROOT}/${path}" content)
  set("${var}" "${content}" PARENT_SCOPE)
endfunction()

function(expect_contains content needle description)
  string(FIND "${content}" "${needle}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Expected ${description}: '${needle}'")
  endif()
endfunction()

read_project_file(java_facade "java/Robot.java")
read_project_file(java_swig "sdk/java/l_master.i")
read_project_file(java_docs "docs/java.md")
read_project_file(bindings_docs "docs/bindings.md")
read_project_file(java_example "examples/robot/RobotExample.java")

expect_contains("${java_facade}" "public final class Robot implements AutoCloseable" "Java public Robot facade")
expect_contains("${java_facade}" "private final NativeRobot nativeRobot" "NativeRobot-backed facade")
expect_contains("${java_facade}" "Loader.loadNativeLibraries()" "automatic native library loading")
expect_contains("${java_swig}" "%rename(NativeRobot) lebai::l_master::Robot;" "SWIG native Robot rename")
expect_contains("${java_docs}" "org.sdk.lebai.NativeRobot" "Java docs for low-level native class")
expect_contains("${bindings_docs}" "Robot.getNative()" "bindings docs for Java low-level access")
expect_contains("${java_example}" "try (Robot robot = new Robot" "Java example uses AutoCloseable facade")
expect_contains("${java_example}" "robot.moveJ(new double[]" "Java example uses primitive array facade")
