set(ROOT "${PROJECT_SOURCE_DIR}")

function(read_project_file var path)
  if(NOT EXISTS "${ROOT}/${path}")
    message(FATAL_ERROR "Expected file to exist: ${path}")
  endif()
  file(READ "${ROOT}/${path}" content)
  set("${var}" "${content}" PARENT_SCOPE)
endfunction()

function(expect_contains content needle description)
  string(FIND "${content}" "${needle}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Expected ${description}: '${needle}'")
  endif()
endfunction()

function(expect_not_contains content needle description)
  string(FIND "${content}" "${needle}" found)
  if(NOT found EQUAL -1)
    message(FATAL_ERROR "Did not expect ${description}: '${needle}'")
  endif()
endfunction()

read_project_file(python_release ".github/workflows/python_release.yml")
read_project_file(python_build ".github/workflows/python_build.yml")
read_project_file(release_workflow ".github/workflows/release.yml")

expect_contains("${python_build}" "pull_request:" "Python build PR trigger")
expect_contains("${python_build}" "ubuntu-24.04-arm" "Python build Linux arm64 runner")
expect_contains("${python_build}" "windows-2022" "Python build Windows x64 runner")
expect_contains("${python_build}" "python-tag: cp39" "Python PR build oldest Linux CPython tag available in manylinux")
expect_contains("${python_build}" "python-tag: cp312" "Python PR build stable Linux CPython tag")
expect_contains("${python_build}" "python-tag: cp315" "Python PR build newest Linux CPython tag")
expect_contains("${python_build}" "PYTHON_GLOB: /opt/python/${{ matrix.python-tag }}-*/bin" "Python PR build per-tag Linux wheel selection")
expect_contains("${python_build}" "scripts/build_python_wheels_manylinux.sh wheelhouse" "Linux wheel build script")
expect_contains("${python_build}" "scripts\\python_wheel_smoke.ps1" "Windows wheel smoke script")

expect_contains("${python_release}" "ubuntu-24.04-arm" "Python release Linux arm64 runner")
expect_contains("${python_release}" "windows-2022" "Python release Windows x64 runner")
expect_contains("${python_release}" "python-tag: cp39" "Python release oldest Linux CPython tag available in manylinux")
expect_contains("${python_release}" "python-tag: cp315" "Python release newest Linux CPython tag")
expect_contains("${python_release}" "PYTHON_GLOB: /opt/python/${{ matrix.python-tag }}-*/bin" "Python release per-tag Linux wheel selection")
expect_contains("${python_release}" "scripts/build_python_wheels_manylinux.sh wheelhouse" "Linux release wheel build script")
expect_contains("${python_release}" "scripts\\python_wheel_smoke.ps1" "Windows release wheel smoke script")
expect_contains("${python_release}" "pattern: lebai-*-whl" "aggregate wheel download")
expect_contains("${python_release}" "python -m twine check dist/*.whl" "wheel validation before publish")
expect_contains("${python_release}" "python -m twine upload" "single PyPI publish step")
expect_contains("${python_release}" "name: lebai-python-wheels" "aggregate wheel artifact")

expect_contains("${release_workflow}" "uses: ./.github/workflows/python_release.yml" "aggregate Python release workflow")
expect_contains("${release_workflow}" "name: lebai-python-wheels" "aggregate Python artifact download")
