name: Linux cpp build
run-name: ${{ github.actor }} Linux cpp build
on: 
  workflow_dispatch: 
  pull_request: 
jobs: 
  linux_cpp_build: 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: install components
        run: sudo apt-get install -y build-essential doxygen graphviz python3-pip python3-dev

      - name: install dependencies
        run: pip3 install -r requirements.txt

      - name: configure
        run: cmake -S. -Bbuild -DBUILD_DEB=ON

      - name: build
        run: cmake --build build
 
  linux_cpp_test:
   needs: linux_cpp_build
   runs-on: ubuntu-latest
   container: registry.cn-shanghai.aliyuncs.com/lebai/l-master:latest
   steps: 
     - name: start nginx
       run: nginx
      
     - name: start daemon
       run: |
        systemctl start l-master-rc
        systemctl start l-master-ds
       
     - name: Checkout
       uses: actions/checkout@v3

     - name: install components
       run: apt-get install -y build-essential doxygen graphviz python3-pip python3-dev

     - name: install dependencies
       run: pip3 install -r requirements.txt

     - name: configure
       run: cmake -S. -Bbuild -DBUILD_TESTING=ON -DBUILD_DOCUMENTATION=ON

     - name: build
       run: cmake --build build
       
     - name: test
       run: cmake --build build --target test
