name: Linux python aarch64 release
run-name: ${{ github.actor }} Linux python aarch64 release
on: 
  workflow_dispatch: 
  # push:
  #  tags:
  #   - v1.*.*
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: read

jobs: 
  linux_python_aarch64_build_and_release: 
    runs-on: [self-hosted, Linux, ARM64]
    container: quay.io/pypa/manylinux2014_aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: ls /opt/python/
      - run: for PYBIN in /opt/python/*/bin;do "${PYBIN}/pip" install -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt; done;
      - run: /opt/python/cp310-cp310/bin/pip install -i https://mirrors.aliyun.com/pypi/simple/ twine==2.0 urllib3==1.24. markdown
      - name: configure
        run: cmake -S. -Bbuild -DBUILD_TESTING=OFF -DBUILD_PYTHON=ON
      - name: build
        run: cmake --build build
      - name: create-whl-dir
        run: mkdir -p whl
      - name: build with python
        run: for PY in /opt/python/*;do
          rm -rf build;
          cmake -S. -Bbuild -DBUILD_TESTING=OFF -DBUILD_PYTHON=ON -DPYTHONPATH=${PY};
          cmake --build build;
          cp build/python/dist/*.whl whl/;
          done;
        
      - name: repair
        run: for PYWHL in whl/*.whl;do
          auditwheel repair ${PYWHL};
          done;
        
      - name: upload Pypi
        run: /opt/python/cp310-cp310/bin/twine upload --skip-existing -u __token__ -p ${{ secrets.PYLEBAI }} wheelhouse/*.whl
