name: Linux cpp release
run-name: ${{ github.actor }} Linux cpp release
on: 
  workflow_dispatch:
  workflow_call:
  push:
   tags:
    - v1.*.*
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
#   contents: read
  pages: write
  id-token: write
#   pull-requests: read

jobs: 
  linux_cpp_build_and_release:
    strategy:
      matrix:
        py-version: [ 3.11 ]
        os-version: [ ubuntu-latest ]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ${{ matrix.os-version }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: check python version
        uses: actions/setup-python@v4.3.0
        with: 
          python-version: ${{ matrix.py-version }}

      - name: install component
        run: sudo apt-get install -y build-essential doxygen graphviz python3-pip python3-dev dpkg-dev

      - name: install dependencies
        run: pip3 install -r requirements.txt

      - name: configure
        run: cmake -S. -Bbuild -DBUILD_DEB=ON -DBUILD_DOCUMENTATION=ON

      - name: build
        run: cmake --build build
        
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload entire repository
          path: './build/html'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        
      - name: Build and pack
        run: |
          cmake --build build
          cd build && cpack && cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: lebai-linux-x64-deb
          path: build/*.deb

      # - name: release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: DebForCPP
      #     allowUpdates: true          