name: Linux dotnet release
run-name: ${{ github.actor }} Linux dotnet release
on:
  workflow_dispatch:
  workflow_call:
jobs:
  linux_dotnet_build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Check dotnet
        run: dotnet --info

      - name: Configure
        run: cmake -S. -Bbuild -DBUILD_DOTNET=ON

      - name: Build
        run: cmake --build build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: lebai-linux-x64-nupkg
          path: build/dotnet/packages/*.nupkg
      - name: Upload native assets
        uses: actions/upload-artifact@v4
        with:
          name: lebai-dotnet-native-linux-x64
          path: build/dotnet/native-assets/**
