name: Linux python build
run-name: ${{ github.actor }} Linux python build
on: 
  workflow_dispatch: 
  pull_request: 
jobs: 
  linux_python_build: 
    runs-on: ubuntu-22.04
    runs:
      using: "node16"
    container: quay.io/pypa/manylinux_2_28_x86_64
    env:
      ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: for PYBIN in /opt/python/*/bin;do "${PYBIN}/pip" install -r requirements.txt; done;
      - run: /opt/python/cp310-cp310/bin/pip install twine==2.0.0 markdown

      - name: create-whl-dir
        run: mkdir -p whl

      - name: Build with python
        run: for PY in /opt/python/*;do
          rm -rf build;
          cmake -S. -Bbuild -DBUILD_PYTHON=ON -DPYTHONPATH=${PY};
          cmake --build build;
          cp build/python/dist/*.whl whl/;
          done;
        
      - name: Repair
        run: for PYWHL in whl/*.whl;do
          auditwheel repair ${PYWHL};
          done;
        
      - name: List wheels.
        run: ls wheelhouse/*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        id: artifact
        with:
          name: lebai-linux-x64-whl
          path: wheelhouse/*.whl