name: Release lebai sdk
on:
  push:
    branches:
      - master

jobs:
  cpp:
    uses: ./.github/workflows/cpp_release.yml
  python:
    uses: ./.github/workflows/python_release.yml
    secrets: inherit
  dotnet:
    uses: ./.github/workflows/dotnet_release.yml
    secrets: inherit
  java:
    uses: ./.github/workflows/java_release.yml
    secrets: inherit
  release:
    needs:
      - cpp
      - python
      - dotnet
      - java
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download linux x64 deb
        uses: actions/download-artifact@v4
        with:
          name: lebai-linux-x64-deb
      - name: Download linux arm64 deb
        uses: actions/download-artifact@v4
        with:
          name: lebai-linux-arm64-deb
      - name: Download dotnet nupkg
        uses: actions/download-artifact@v4
        with:
          name: lebai-dotnet-nupkg
      - name: Download Java jars
        uses: actions/download-artifact@v4
        with:
          name: lebai-java-jars
      - name: Download Python wheels
        uses: actions/download-artifact@v4
        with:
          name: lebai-python-wheels
      - name: Download win x64 exe
        uses: actions/download-artifact@v4
        with:
          name: lebai-win-x64-exe
      - name: Display structure of downloaded files
        run: ls -l
      - name: Extract Project Version
        id: extract_version
        run: |
          # Extract the project version from CMakeLists.txt
          version=$(awk '/project\s*\(/,/)/' CMakeLists.txt | grep -Po 'VERSION\s*\K[0-9]+\.[0-9]+\.[0-9]+')
          echo "version_tag=v$version" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.version_tag }}
          allowUpdates: true
          artifacts: |
            *.exe,
            *.deb,
            *.nupkg,
            *.jar,
            *.whl
