name: Windows python release
run-name: ${{ github.actor }} Windows python release
on: 
  workflow_dispatch:
  workflow_call:
  push:
   tags:
    - v1.*.*
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: read

jobs:
  windows_cp38_release:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Check cmake
        run: cmake --version
      - name: Install python-dev-tools
        run: python.exe -m pip install python-dev-tools setuptools wheel twine markdown

      - name: CMake configure
        run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DBUILD_PYTHON=ON -DBUILD_DOCUMENTATION=OFF
      - name: CMake build
        run: cmake --build build --config release
      - name: Upload Pypi
        run: twine upload --skip-existing -u __token__ -p ${{ secrets.PYLEBAI }} build/python/dist/*.whl
      - name: Upload packages
        uses: actions/upload-artifact@v3
        id: artifact-38
        with:
          name: lebai-win-x64-38-whl
          path: |
            build/python/dist/*.whl        
  windows_cp39_release:
    runs-on: windows-latest 
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Check cmake
        run: cmake --version
      - name: Install python-dev-tools
        run: python.exe -m pip install python-dev-tools setuptools wheel twine markdown

      - name: CMake configure
        run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DBUILD_PYTHON=ON -DBUILD_DOCUMENTATION=OFF
      - name: CMake build
        run: cmake --build build --config release
      - name: Upload Pypi
        run: twine upload --skip-existing -u __token__ -p ${{ secrets.PYLEBAI }} build/python/dist/*.whl
      - name: Upload packages
        uses: actions/upload-artifact@v3
        id: artifact-39
        with:
          name: lebai-win-x64-39-whl
          path: |
            build/python/dist/*.whl
  windows_cp310_release:
    runs-on: windows-latest 
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check cmake
        run: cmake --version
      - name: Install python-dev-tools
        run: python.exe -m pip install python-dev-tools setuptools wheel twine markdown

      - name: CMake configure
        run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DBUILD_PYTHON=ON -DBUILD_DOCUMENTATION=OFF
      - name: CMake build
        run: cmake --build build --config release
      - name: Upload Pypi
        run: twine upload --skip-existing -u __token__ -p ${{ secrets.PYLEBAI }} build/python/dist/*.whl
      - name: Upload packages
        uses: actions/upload-artifact@v3
        id: artifact-310
        with:
          name: lebai-win-x64-310-whl
          path: |
            build/python/dist/*.whl
  windows_cp311_release:
    runs-on: windows-latest 
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Check cmake
        run: cmake --version
      - name: Install python-dev-tools
        run: python.exe -m pip install python-dev-tools setuptools wheel twine markdown

      - name: CMake configure
        run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DBUILD_PYTHON=ON -DBUILD_DOCUMENTATION=OFF
      - name: CMake build
        run: cmake --build build --config release
      - name: Upload Pypi
        run: twine upload --skip-existing --verbose -u __token__ -p ${{ secrets.PYLEBAI }} build/python/dist/*.whl
      - name: Upload packages
        uses: actions/upload-artifact@v3
        id: artifact-311
        with:
          name: lebai-win-x64-311-whl
          path: |
            build/python/dist/*.whl
  # windows_cp312_release:
  #   runs-on: windows-latest 
  #   steps: 
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.12'
  #     - name: Check cmake
  #       run: cmake --version
  #     - name: Install python-dev-tools
  #       run: python.exe -m pip install python-dev-tools setuptools wheel twine markdown

  #     - name: CMake configure
  #       run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DBUILD_PYTHON=ON -DBUILD_DOCUMENTATION=OFF
  #     - name: CMake build
  #       run: cmake --build build --config release
  #     - name: Upload Pypi
  #       run: twine upload --skip-existing -u __token__ -p ${{secrets.PYLEBAI2024}} build/python/dist/*.whl
