name: Windows python release
run-name: ${{ github.actor }} Windows python release
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - v1.*.*
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: read

jobs:
  windows_python_release:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check cmake
        run: cmake --version
      - name: Check Python version
        run: python.exe --version
      - name: Install python-dev-tools
        run: python.exe -m pip install python-dev-tools setuptools wheel twine markdown

      - name: CMake configure
        run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DBUILD_PYTHON=ON -DBUILD_TESTING=OFF -DBUILD_DOCUMENTATION=OFF -DPython3_EXECUTABLE="${{ env.pythonLocation }}\python.exe" -DPYTHON_EXECUTABLE="${{ env.pythonLocation }}\python.exe"
      - name: CMake build
        run: cmake --build build --config release
      - name: Upload Pypi
        run: twine upload --skip-existing --verbose -u __token__ -p ${{ secrets.PYLEBAI }} build/python/dist/*.whl
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: lebai-win-x64-${{ matrix.python-version }}-whl
          path: |
            build/python/dist/*.whl