name: Windows python release
run-name: ${{ github.actor }} Windows python release
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - v1.*.*
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: read

jobs:
  windows_python_release:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set Python version for artifact name
        run: |
          $version = "${{ matrix.python-version }}".Replace(".", "")
          echo "PYTHON_VERSION_NO_DOT=$version" >> $env:GITHUB_ENV
      - name: Check cmake
        run: cmake --version
      - name: Check Python version
        run: python.exe --version
      - name: Install python-dev-tools
        run: python.exe -m pip install python-dev-tools setuptools wheel twine delvewheel markdown

      - name: CMake configure
        run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DBUILD_PYTHON=ON -DBUILD_TESTING=OFF -DBUILD_DOCUMENTATION=OFF -DPython3_EXECUTABLE="${{ env.pythonLocation }}\python.exe" -DPYTHON_EXECUTABLE="${{ env.pythonLocation }}\python.exe"
      - name: CMake build
        run: cmake --build build --config release
      - name: List built wheels
        run: dir build\python\dist\
      - name: Repair wheels with delvewheel
        run: |
          New-Item -ItemType Directory -Force -Path repaired_wheels
          delvewheel repair --add-path build\Release -w repaired_wheels build\python\dist\*.whl
      - name: List repaired wheels
        run: dir repaired_wheels\
      - name: Upload Pypi
        run: twine upload --verbose -u __token__ -p ${{ secrets.PYLEBAI }} repaired_wheels/*.whl
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: lebai-win-x64-${{ env.PYTHON_VERSION_NO_DOT }}-whl
          path: |
            repaired_wheels/*.whl