name: Windows python release
run-name: ${{ github.actor }} Windows python release
on: 
  workflow_dispatch: 
  push:
   tags:
    - v1.*.*
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: read

jobs: 
  windows_python_build:
    runs-on: windows-latest 
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check cmake
        run: cmake --version
      - name: Install python-dev-tools
        run: python.exe -m pip install python-dev-tools setuptools wheel twine

      - name: Configure
        run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DBUILD_PYTHON=ON -DBUILD_DOCUMENTATION=OFF
      - name: Build
        run: cmake --build build --config release
      - name: upload Pypi
        run: twine upload -u ${{ secrets.USRNAME }} -p ${{ secrets.PASSWD }} build/python/dist/*.whl

      # - name: Publish package
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}   